function fileHandler_html4(l,e){if("upload"==KUPLOADTOP.G_CURRKUPLOADER._config.mode){var f=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileCount,a=!0,b=[],m={file:l,name:getFileName(e,!1),size:"",type:"",lastModifiedDate:""};b.push(m);var m=[],g=KUPLOADTOP.G_CURRKUPLOADER.frameWin.getTotalFileCount(),k=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.duplication,d=0,p=!1;"0"==KUPLOADTOP.G_CURRKUPLOADER._config.allowDuplicationFile&&(p=sameFileCheck(b[0]));if(p)"0"==k&&alert(b[0].name+" "+RAONKUpload_Lang.message_duplication_file);
else{var k=!1,p=KUPLOADTOP.G_CURRKUPLOADER._config.extension,t=p.extArr.length;if(0<t){var u=p.allowOrLimit;if("1"==u){for(var q=getExtension(b[0].name),n=0;n<t;n++)if(p.extArr[n]==q){k=!0;break}k||m.push(q)}else for(q=getExtension(b[0].name),n=0;n<t;n++)if(p.extArr[n]==q){k=!1;m.push(q);break}else k=!0}else k=!0;calcTotalSize();p=TOTALREALFILENUM;if(0!=f&&p+1>f){alert(RAONKUpload_Lang.file_maximum+" "+f+RAONKUpload_Lang.message_limit_num);return}if(k){var v=f="";document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID)&&
(v=document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value);null==e&&(e="");(f=e)&&(f=KUPLOADTOP.RAONKUPLOAD.util.trim(f));if("undefined"==typeof f||null==f)f="undefined"==typeof filePathSplit[0]||null==filePathSplit[0]?"":filePathSplit[0].substring(0,filePathSplit[0].lastIndexOf(KUPLOADTOP.RAONKUPLOAD.UserAgent.osSeparator)+1)+b[0].name;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAddEvent)try{var h=b[0].file,c={strName:b[0].name,nSize:b[0].size,nIndex:g+d,strPath:f,objFile:h},a=
KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_BeforeAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,c);!1!==a&&(a=!0)}catch(w){}if(a){a=b[0].type;if(null==a||void 0==a||""==a)a="application/octet-stream";a={file:b[0].file,guid:"",fileIdx:"",webPath:"",originName:b[0].name,fileSize:b[0].size,uploadName:"",uploadPath:"",logicalPath:"",status:"ready",fileExt:"",isDelete:"n",isWebFile:"n",localPath:f,customValue:"",responseCustomValue:"",headerEx:"",lastModifiedDate:b[0].lastModifiedDate,mimeType:a};RESULTFILELIST.push(a);
a.isFolder="0";addFileList(a);if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEvent)try{calcTotalSize(),h=b[0].file,c={strName:b[0].name,nSize:b[0].size,nIndex:g+d,strPath:a.localPath,objFile:h},KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,c)}catch(x){}d++;b=document.getElementById("files_container");KUPLOADTOP.G_CURRKUPLOADER.TagID=KUPLOADTOP.RAONKUPLOAD.util.makeGuidTagName();h=document.createElement("form");h.setAttribute("id","form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);
h.setAttribute("method","post");h.setAttribute("enctype","multipart/form-data");h.setAttribute("encoding","multipart/form-data");c=document.createElement("span");c.className="input_image_add";c.innerHTML=RAONKUpload_Lang.btn_add;""!=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor&&(c.style.background=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor);""!=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor&&(c.style.color=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor);var r=document.createElement("input");
r.setAttribute("id","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);r.setAttribute("name","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);r.setAttribute("type","file");KUPLOADTOP.RAONKUPLOAD.util.addEvent(r,"change",function(){fileHandler_html4(r,r.value)});KUPLOADTOP.RAONKUPLOAD.util.addEvent(r,"blur",function(){focusHandler(r)});g=document.createElement("input");g.setAttribute("id","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);g.setAttribute("name","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);g.setAttribute("type",
"hidden");g.setAttribute("value","0");h.appendChild(c);h.appendChild(r);h.appendChild(g);c=document.createElement("div");c.appendChild(h);b.appendChild(c);c.previousSibling&&(c.previousSibling.style.display="none",c.previousSibling.childNodes[0].childNodes[1].tabIndex="-1")}}}displayTotalSizeAndNum();b=m.length;0<b&&(h="",c=KUPLOADTOP.G_CURRKUPLOADER._config.extension.extArr,"1"==u?1<b?(h=RAONKUpload_Lang.message_not_allow_exts,h=h.replace("{0}",b),h=h.replace("{1}",c)):(h=m[0]+" "+RAONKUpload_Lang.message_not_allow_ext,
h=h.replace("{0}",c)):1<b?(h=RAONKUpload_Lang.message_not_limit_exts,h=h.replace("{0}",b),h=h.replace("{1}",c)):(h=m[0]+" "+RAONKUpload_Lang.message_not_limit_ext,h=h.replace("{0}",c)),alert(h));"1"==KUPLOADTOP.G_CURRKUPLOADER._config.use_file_sort&&"1"==KUPLOADTOP.G_CURRKUPLOADER._config.auto_sort&&"1"!=KUPLOADTOP.G_CURRKUPLOADER._config.sort_field&&sortTotalFileList(KUPLOADTOP.G_CURRKUPLOADER._config.sort_field,KUPLOADTOP.G_CURRKUPLOADER._config.sort_ascdesc);calcTotalSize();fileListSortIconReset();
setFileListBorder();setTabOrder();setListvalue();setLargeFileAllList();1==v&&(document.getElementById("file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).focus(),document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundImage="url("+KUPLOADTOP.G_CURRKUPLOADER._config.webPath.image+"img_bt_line.png)",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundRepeat="no-repeat",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionY=
"2px",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionX="1px",document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value="1",G_FileHandlerControl=0);"thumbs"==KUPLOADTOP.G_CURRKUPLOADER._config.views&&thumbsViewWithCanvas();if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEndTimeEvent&&0<d)try{KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID)}catch(y){}}}
function processUploadHtml4(){if(!KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){var l=getDialogDocument();0==upload_complete_count&&(G_UploadStartTime=(new Date).getTime()/1E3);var e=document.getElementById("files_container").getElementsByTagName("form"),f=0;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile)for(var a=0;a<uploaders[upload_complete_count];a++)RESULTFILELIST[a].file&&"complete"==RESULTFILELIST[a].status&&f++;e=e[upload_complete_count+f];f=document.charset;document.charset="utf-8";
var b=upload_complete_count.toString();b==(uploaders.length-1).toString()&&(b+="z");RESULTFILELIST[uploaders[upload_complete_count]].guid=KUPLOADTOP.RAONKUPLOAD.util.makeGuid();var m=e.getElementsByTagName("input"),g=m[0],m=m[1];e.removeChild(m);for(var k=0,d=RESULTFILELIST.length,a=0;a<uploaders[upload_complete_count];a++)"n"==RESULTFILELIST[a].isDelete&&(k+=parseInt(RESULTFILELIST[a].fileSize,10));for(a=uploaders[upload_complete_count]+1;a<d;a++)"y"==RESULTFILELIST[a].isWebFile&&(k+=parseInt(RESULTFILELIST[a].fileSize,
10));d=""+("kc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c02"+KUPLOADTOP.RAONKSolution.Agent.vertical);d+="k01"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].guid+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k14"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].originName+
KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k15"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k16"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRuleEx+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k17"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.folderNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k20"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
b+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k21"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].customValue+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k22"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k23"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k24"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.allowedZeroFileSize+KUPLOADTOP.RAONKSolution.Agent.vertical;
"1"==KUPLOADTOP.G_CURRKUPLOADER._config.security.fileExtensionDetector&&(d+="k29"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical);var p=KUPLOADTOP.G_CURRKUPLOADER._config.maxOneFileSize;0!=p&&(d+="k40"+KUPLOADTOP.RAONKSolution.Agent.formfeed+p+KUPLOADTOP.RAONKSolution.Agent.vertical);var t=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileSize;0!=t&&(d+="k41"+KUPLOADTOP.RAONKSolution.Agent.formfeed+t+KUPLOADTOP.RAONKSolution.Agent.vertical,d+="k42"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
k+KUPLOADTOP.RAONKSolution.Agent.vertical);a=document.createElement("input");a.type="hidden";b=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(d);a.name=b.name;a.value=b.value;e.insertBefore(a,g);k=G_FormData.length;b=[];for(d=0;d<k;d++){var u=G_FormData[d].form_value,u="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(u).value:encodeURIComponent(u),q=document.createElement("input");q.type="hidden";q.name=G_FormData[d].form_name;q.value=
u;e.insertBefore(q,g);b.push(q)}var n=document.createElement("div"),d=KUPLOADTOP.RAONKUPLOAD.util.getDefaultIframeSrc();n.innerHTML='<iframe name="uploadframe" id="uploadframe" style="display:none;" src="'+d+'"></iframe>';n.style.display="none";document.body.appendChild(n);KUPLOADTOP.RAONKUPLOAD.util.addEvent(n.firstChild,"load",function(){n.firstChild.contentWindow.postMessage("check","*")},!0);var v=function(c,a){var d=getUploadedFileListObj();try{KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError(KUPLOADTOP.G_CURRKUPLOADER.ID,
{strType:"upload",strCode:c,strMessage:a,arrUploadedFileList:d})}catch(b){}if(1==G_MultiTranferCheck)G_MultiTranferCheck=4;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&fileListReset()}catch(g){}clearInterval(G_IntervalObj);PREVIOUSUPLOADEDSIZE=0;l.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;"1"==KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.use&&
(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()};if(window.postMessage){var h=function(c){document.body.removeChild(n);KUPLOADTOP.RAONKUPLOAD.util.removeEvent(window,"message",h);c=KUPLOADTOP.RAONKUPLOAD.util.trim(c.data);c=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(c);if(0==c.indexOf("[OK]"))if(c=c.replace("[OK]",""),c=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(c),
"C012|response data decrypt error"==c)c=c.split("|"),v(c[0],c[1]);else{c=c.split(KUPLOADTOP.RAONKSolution.Agent.formfeed);var a=c[0],d="",b="",g=a.indexOf("::");-1<g&&(d=a.substring(0,g),a=a.substring(g+2,a.length));g=a.indexOf(":");-1<g&&(b=a.substring(0,g),a=a.substring(g+1,a.length));g="";g=a.length;"|"==a.substring(g-1,g)?(a=a.substring(0,g-1),g=getFileName(a,!1),a=a.substring(0,a.lastIndexOf("/"+g))):g=getFileName(a,!1);RESULTFILELIST[uploaders[upload_complete_count]].uploadName=g;RESULTFILELIST[uploaders[upload_complete_count]].uploadPath=
a;RESULTFILELIST[uploaders[upload_complete_count]].fileSize=c[2];RESULTFILELIST[uploaders[upload_complete_count]].status="complete";RESULTFILELIST[uploaders[upload_complete_count]].logicalPath="";RESULTFILELIST[uploaders[upload_complete_count]].responseCustomValue=c[1];""!=b&&(RESULTFILELIST[uploaders[upload_complete_count]].originName=b);RESULTFILELIST[uploaders[upload_complete_count]].hashValue=d;KUPLOADTOP.G_CURRKUPLOADER.uploadedTaskId="";KUPLOADTOP.G_CURRKUPLOADER.uploadedSize=0;PREVIOUSUPLOADEDSIZE+=
parseInt(c[2],10);clearInterval(G_IntervalObj);uploadProgressComplete_html4(KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(c[2]));upload_complete_count++;if(KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useUploadingCancelEvent){c={bAutoTransferFlag:!1,arrUploadedFileList:getUploadedFileListObj()};try{KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_UploadingCancel(KUPLOADTOP.G_CURRKUPLOADER.ID,c)}catch(e){}}if(1==G_MultiTranferCheck)G_MultiTranferCheck=3;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&
fileListReset()}catch(f){}PREVIOUSUPLOADEDSIZE=0;l.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;"1"==KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.use&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()}else upload_complete_count==
TOTALUPLOADNUM?(PREVIOUSUPLOADEDSIZE=0,l.getElementById("RAON_K_UP_upload_size").innerHTML="-",totalUploadComplete(),"1"==KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.use&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1)):(c=uploaders.indexOf(uploaders[upload_complete_count]),adjustUploadFileListScroll(c,upload_complete_count,TOTALUPLOADNUM),processUploadHtml4())}else if(0==c.indexOf("[FAIL]")){c=c.replace("[FAIL]","");c=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(c);c=
KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(c);a="";"020"==c.code?(a=RAONKUpload_Lang.message_limit_one_size,a=a.replace("{0}",KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(p).toString)):a="021"==c.code?RAONKUpload_Lang.message_file_ext_detect_html4:"022"==c.code?RAONKUpload_Lang.file_maximum+" "+KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(t).toString+RAONKUpload_Lang.message_limit_size:c.message;d=0;if("020"==c.code||"021"==c.code||"022"==c.code){for(b=0;b<uploaders[upload_complete_count];b++)"y"==RESULTFILELIST[b].isDelete&&
d++;var k=uploaders[upload_complete_count]-d;setSelectFile(k,0);k=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm;KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1;KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID);KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=k}if("022"==c.code)for(g=RESULTFILELIST.length,b=uploaders[upload_complete_count];b<g;b++)"y"==RESULTFILELIST[b].isDelete?d++:"n"==RESULTFILELIST[b].isWebFile&&
(k=b-d,setSelectFile(k,0),k=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm,KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1,KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID),KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=k,b--,g--);v(c.code,a)}};KUPLOADTOP.RAONKUPLOAD.util.addEvent(window,"message",h)}e.setAttribute("target","uploadframe");e.setAttribute("action",KUPLOADTOP.G_CURRKUPLOADER._config.handlerUrl);
l.getElementById("RAON_K_UP_current_upload_file_name").innerHTML=" "+RESULTFILELIST[uploaders[upload_complete_count]].originName;e.submit();document.charset=f;e.removeChild(a);for(a=k-1;0<=a;a--)e.removeChild(b[a]);e.insertBefore(m,g.nextSibling);uploadProgress_html4(upload_complete_count,TOTALUPLOADNUM,50)}}
function uploadProgress_html4(l,e,f){var a=getDialogDocument();adjustUploadFileListScroll(l-1,l,e);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l]).style.width="0%";G_IntervalObj=setInterval(function(){b()},400);var b=function(){var b;b=0;if(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l])){b=a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l]).style.width.split("%");b=Math.round(1*b[0]*f/100);b++;if(b==parseInt(3*f/5,10)+1)m("1");else if(b==parseInt(4*f/5,10)+
1)m("2");else if(b==parseInt(9*f/10,10)+1)m("3");else if(b==parseInt(24*f/25,10)+1){m("4");return}if(1==b)if(a.getElementById("RAON_K_UP_upload_count"))a.getElementById("RAON_K_UP_upload_count").innerHTML=l+1+"/"+e;else return;var k=parseInt(1/f*100*b,10);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l])&&(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[l]).style.width=k+"%",a.getElementById("RAON_K_UP_current_upload_progress_bar")&&(a.getElementById("RAON_K_UP_current_upload_progress_bar").style.width=
k+"%"),b=parseInt(1*l/e*100,10)+parseInt(parseInt(1/f*100*b,10)/e,10),a.getElementById("RAON_K_UP_total_upload_percent")&&(a.getElementById("RAON_K_UP_total_upload_percent").innerHTML=b+"%",a.getElementById("RAON_K_UP_total_upload_progress_bar")&&(a.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=b+"%",a.getElementById("RAON_K_UP_upload_size")&&0==PREVIOUSUPLOADEDSIZE&&(a.getElementById("RAON_K_UP_upload_size").innerHTML="-"))))}},m=function(a){"1"==a?(clearInterval(G_IntervalObj),
G_IntervalObj=setInterval(function(){b()},800)):"2"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){b()},1E3)):"3"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){b()},1200)):"4"==a&&clearInterval(G_IntervalObj)};null==KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval&&(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=setInterval(function(){a.getElementById("RAON_K_UP_process_time").innerHTML=viewTime(++KUPLOADTOP.G_CURRKUPLOADER.processTime)},1E3))}
function uploadProgressComplete_html4(l){var e=getDialogDocument(),f=uploaders[upload_complete_count];if(void 0!=f){var a=parseInt(1*(f+1)/TOTALUPLOADNUM*100,10);e.getElementById("RAON_K_UP_current_upload_progress_bar").style.width="100%";e.getElementById("RAON_K_UP_uploadFileProgress_"+f).style.width="100%";e.getElementById("RAON_K_UP_uploadFilePercent_"+f).style.color="";e.getElementById("RAON_K_UP_uploadFilePercent_"+f).innerHTML="100%";e.getElementById("RAON_K_UP_uploadFileSize_"+f).innerHTML=
l.toString;UPLOADIDX++;e.getElementById("RAON_K_UP_upload_count").innerHTML=upload_complete_count+1+"/"+TOTALUPLOADNUM;e.getElementById("RAON_K_UP_total_upload_percent").innerHTML=a+"%";e.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=a+"%";e.getElementById("RAON_K_UP_upload_size").innerHTML=KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(PREVIOUSUPLOADEDSIZE).toString;100==a&&(clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval),KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=
null,KUPLOADTOP.G_CURRKUPLOADER.processTime=0)}};
