(function(){function f(a){var d={};a=a.split(",");for(var c=0;c<a.length;c++)d[a[c]]=!0;return d}var p=/^<([-A-Za-z0-9_]+)((?:\s+\w+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,v=/^<\/([-A-Za-z0-9_:]+)[^>]*>/,x=/([-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,u=/^<([-A-Za-z0-9_:-]+)((?:\s+[a-zA-Z_0-9:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,y=/([-A-Za-z0-9_:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
z=f("colgroup,col"),A=f("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");f("area,base,basefont,br,col,frame,img,input,isindex,link,meta,param,embed");var B=f("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul,h1,h2,h3,h4,h5,h6,figure"),w=f("a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var"),
C=f("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),D=f("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),E=f("");"undefined"==typeof RAONK_EDITOR&&(RAONK_EDITOR={});RAONK_EDITOR.HTMLParser=function(a,d,c){function t(a,b,m,n){b=b.toLowerCase();if(B[b]){for("table"!=h.last()&&"tbody"!=h.last()||"td"!=b||t("","tr","","");h.last()&&w[h.last()];)l("",h.last());"p"!=h.last()||"table"!=b&&"hr"!=b&&"center"!=b&&"figure"!=b||l("","p")}C[b]&&h.last()==
b&&l("",b);(n=A[b]||!!n)||h.push(b);if(c.start){var e=[];a=p.test(a)?x:y;m.replace(a,function(a,b,m,c,n){m=m?m:c?c:n?n:D[b]?b:"";c="";""!=a&&(a=a.substring(a.indexOf(b)+b.length),a=a.substring(a.indexOf("=")+1),a=a.replace(/^\s+/,""),c=a.substring(0,1),"'"!=c&&'"'!=c&&(c=""));e.push({name:b,value:m,escaped:m.replace(/(^|[^\\])"/g,'$1\\"'),quotationmark:c})});c.start&&c.start(b,e,n)}}function l(a,b){if(b)for(b=b.toLowerCase(),m=h.length-1;0<=m&&h[m]!=b;m--);else var m=0;if(0<=m){for(var n=h.length-
1;n>=m;n--)c.end&&c.end(h[n]);h.length=m}}var b,e,h=[],f=a;for(h.last=function(){return this[this.length-1]};a;){e=!0;if(h.last()&&E[h.last()])a=a.replace(new RegExp("(.*)</"+h.last()+"[^>]*>"),function(a,b){b=b.replace(/\x3c!--(.*?)--\x3e/g,"$1").replace(/<!\[CDATA\[(.*?)]]\x3e/g,"$1");c.chars&&c.chars(b);return""}),l("",h.last());else{var g=a.indexOf("<");b=a.indexOf(">")+1;var q=a.substring(g,b);if(0==a.indexOf("\x3c!--"))b=a.indexOf("--\x3e"),0<=b&&(c.comment&&c.comment(a.substring(4,b)),a=a.substring(b+
3),e=!1);else if(0==a.toLowerCase().indexOf("<?xml"))b=a.indexOf("/>"),0<=b&&(a=a.substring(b+2),e=!1);else if(0!=a.indexOf("<")&&"</"+h.last()+">"==q.replace(/ /ig,""))e=a.substring(0,g),a=a.substring(b),a=e+"</"+h.last()+">"+a,e=!0;else if(0==a.indexOf("</")){if(b=a.match(v))a=a.substring(b[0].length),b[0].replace(v,l),e=!1}else if(0==a.indexOf("<"))if(b=a.match(p))a=a.substring(b[0].length),b[0].replace(p,t),e=!1;else if(b=a.match(u))a=a.substring(b[0].length),b[0].replace(u,t),e=!1;else if("1"==
KEDITORTOP.G_CURRKEDITOR._config.removeIncorrectAttribute&&(b=a.indexOf("<"),q=a.indexOf(">"),0==b&&0<q)){var k=a.substring(0,q+1),r=g=b=0;0<k.indexOf('\ub9d1\uc740=""')?(b=k.indexOf('\ub9d1\uc740=""'),g=5,r=k.split('\ub9d1\uc740=""').length):0<k.indexOf("\ub9d1\uc740=''")&&(b=k.indexOf("\ub9d1\uc740=''"),g=5,r=k.split("\ub9d1\uc740=''").length);if(2==r&&0<b&&(q=a.substring(q+1),r=k.substring(0,b).lastIndexOf(" "),r<b+g))if(a=k.substring(r,b+g),k=k.replace(a,""),a=k+q,b=a.match(p))a=a.substring(b[0].length),
b[0].replace(p,t),e=!1;else if(b=a.match(u))a=a.substring(b[0].length),b[0].replace(u,t),e=!1}e&&(b=a.indexOf("<"),e=0>b?a:a.substring(0,b),a=0>b?"":a.substring(b),c.chars&&(h.last()&&w[h.last()]&&"textarea"!=h.last()&&"script"!=h.last()&&(b=!1,g=RegExp("\\S\\n","g"),g.test(e)&&(b=!0),g=RegExp("\\n\\S","g"),g.test(e)&&(b=!0),g=RegExp("\\S\\n\\S","g"),g.test(e)&&(b=!0),b?e=e.replace(/\n/g," "):(g=RegExp("\\n\\n","g"),g.test(e)&&""==e.trim()?e=e.replace(/\n\n/g,""):e==unescape("%20%20")&&(b=new RegExp(unescape("%20"),
"g"),e=e.replace(b,"&nbsp;")))),"1"==KEDITORTOP.G_CURRKEDITOR._config.replaceSpace&&d&&(b=new RegExp(unescape("%20%20"),"g"),e=e.replace(b,"&nbsp; ")),c.chars(e)))}if(a==f)throw"Parse Error: "+a;f=a}l()};RAONK_EDITOR.HTMLParser.HTMLtoXML=function(a,d){var c="";RAONK_EDITOR.HTMLParser(a,d,{start:function(a,d,b){c+="<"+a;for(a=0;a<d.length;a++)c="href"==d[a].name||"src"==d[a].name?c+(" "+d[a].name+"="+d[a].quotationmark+d[a].value+d[a].quotationmark):""!=d[a].quotationmark?c+(" "+d[a].name+"="+d[a].quotationmark+
d[a].value+d[a].quotationmark):c+(" "+d[a].name+'="'+d[a].escaped+'"');c+=(b?"/":"")+">"},end:function(a){z[a]||(c+="</"+a+">")},chars:function(a){c+=a},comment:function(a){c="0"==KEDITORTOP.G_CURRKEDITOR._config.removeComment?c+("\x3c!--"+a+"--\x3e"):c+""}});return c};RAONK_EDITOR.HTMLParser.RemoveOfficeTag=function(a,d){if(""==a||void 0==a)return"";a=RAONK_EDITOR.HTMLParser.RemoveOfficeTag2(a);a=KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp(a);d&&(a=a.replace(/>\s+</g,"><"));return a};RAONK_EDITOR.HTMLParser.RemoveOfficeTag2=
function(a){var d=RegExp("<o:p></o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(d,"");a=a.replace(/\slang=[\"]?en-us[\"]?/gi,"");"1"==KEDITORTOP.G_CURRKEDITOR._config.removeMsoClass&&(a=a.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,""));a=a.replace(/&quot;/gi,"&quot_raonk");d=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi");a=a.replace(d,"");d=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"@%\\.\\\\_]+; ?",
"gi");a=a.replace(d,"");d=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi");a=a.replace(d,"$1");a=a.replace(/&quot_raonk/gi,"&quot;");d=RegExp("<v:shapetype ([^>]+)>[\\s\\S]*?</v:shapetype>","gi");a=a.replace(d,"");d=RegExp("<v:shape [^>]+>[\\s\\S]*?(<img [^>]+>)*?</v:shape>","gi");a=a.replace(d,"$1");d=RegExp("<v:shape ([^>]+)>[\\s\\S]*?</v:shape>","gi");a=a.replace(d,"");return a=a.replace(/<\!\[if ppt\]>/gi,"")};RAONK_EDITOR.HTMLParser.CleanNestedHtml=function(a,d,c,f){function l(a,b){for(var c=
0,d=a.childNodes.length,e=0;e<d;e++)3!=a.childNodes[e].nodeType&&(b&&(c+=l(a.childNodes[e],b)),c++);return c}function b(a){for(var b="",c=Array(a.childNodes.length),d=0;d<c.length;d++){c[d]=[];c[d].push(a.childNodes[d]);e(a.childNodes[d],c[d]);var h=d,g=c[d],f=[],k=0;a:for(;k<g.length;k++){for(var l=0;l<f.length;l++)if(f[l]==g[k])continue a;f[f.length]=g[k]}c[h]=f;b+=c[d].join("")}return b}function e(a,b){for(var c=a.childNodes,d=0;d<c.length;d++)b.push(c[d]),c[d].hasChildNodes()&&e(c[d],b);for(var c=
0,f;c<b.length;c++){d=b[c];if(1==d.nodeType){f=d.nodeName;if(-1==(" "+q.join(" ").toUpperCase()+" ").search(" "+f.toUpperCase()+" ")){b.splice(c,1);c--;continue}f=d;for(var g="",k=0,l=void 0;k<f.attributes.length;k++)l=f.attributes[k],1==l.specified&&("style"==l.name?(l=h(f),""!=l&&(g+=' style="'+h(f)+'"')):""!=l.value&&(g+=" "+l.name+'="'+l.value+'"'));f=g;d="<"+d.nodeName.toLowerCase()+f+">"}else 3==d.nodeType&&(d=d.nodeValue.replace(/\n/g,""));b[c]=d}return b}function h(a){for(var b="",c=0,d=g.length,
e;c<d;c++)a.currentStyle?e=a.currentStyle[g[c]]:window.getComputedStyle&&(e=document.defaultView.getComputedStyle(a,null).getPropertyValue(g[c])),b+=g[c]+":"+e+";";return b}var p=50,g=[],q="p a abbr acronym applet b basefont bdo big br button cite code del dfn em font i iframe img input ins kbd label map object q s samp script select small strike strong sub sup textarea tt u var".split(" ");"undefined"!=typeof c&&(p=parseInt(c));c="p";f&&(c=f);var k=a._DOC.getElementsByTagName(c);f=!1;c=0;for(var r=
k.length;c<r;c++)if(l(k[c],!0)>p){f=!0;break}f&&(showProcessingBackground(),setTimeout(function(){a._BODY.contentEditable=!1;try{if("2"==d)KEDITORTOP.RAONKEDITOR.Commands("select_all",a.ID),KEDITORTOP.RAONKEDITOR.Commands("remove_css",a.ID),KEDITORTOP.RAONKEDITOR.Commands("remove_format",a.ID),a._FRAMEWIN.setFocusToBody(),setTimeout(function(){a._FRAMEWIN.doSetCaretPosition(a._BODY.firstChild,0)},20);else for(var c=0,e=k.length,f;c<e;c++)l(k[c],!0)>p&&(f=b(k[c]),f=RAONK_EDITOR.HTMLParser.HTMLtoXML(f),
k[c].innerHTML=f)}catch(g){}hideProcessingBackground();a._BODY.contentEditable=!0},G_Progress_LoadTime))};RAONK_EDITOR.HTMLParser.makeMap=function(a){return f(a)}})();
